default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_youtube_feed_development

test:
  <<: *default
  database: my_youtube_feed_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
    migrations_paths: db/cable_migrate
