service: my_youtube_feed

image: mousu/myf

servers:
  web:
    - ec2-3-112-39-246.ap-northeast-1.compute.amazonaws.com

deploy_timeout: 120

registry:
  server: 637423506634.dkr.ecr.ap-northeast-1.amazonaws.com
  username: AWS
  password:
    - AWS_ECR_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_YOUTUBE_CLIENT_ID
    - GOOGLE_YOUTUBE_CLIENT_SECRET

asset_path: /rails/public/assets

ssh:
  user: admin

builder:
  arch: amd64
